import { Recipe } from '../types';
import html2pdf from 'html2pdf.js';

export const useRecipeExport = () => {
    const downloadAsPDF = async (recipe: Recipe, elementId: string = 'recipe-content') => {
        try {
            const element = document.getElementById(elementId);
            if (!element) {
                throw new Error('Recipe content not found');
            }

            // Clone the element to modify for PDF
            const clone = element.cloneNode(true) as HTMLElement;

            // Add print-friendly styles
            const styleSheet = document.createElement('style');
            styleSheet.textContent = `
                * { 
                    -webkit-print-color-adjust: exact !important;
                    print-color-adjust: exact !important;
                }
                body { margin: 0; padding: 0; }
                .print\\:hidden, button, nav, header, footer { display: none !important; }
            `;
            clone.insertBefore(styleSheet, clone.firstChild);

            const opt = {
                margin: [15, 15, 15, 15] as [number, number, number, number],
                filename: `${recipe.title.replace(/[^a-z0-9]/gi, '_')}.pdf`,
                image: { type: 'jpeg' as const, quality: 0.98 },
                html2canvas: {
                    scale: 2,
                    useCORS: true,
                    logging: false,
                    letterRendering: true
                },
                jsPDF: {
                    unit: 'mm',
                    format: 'a4',
                    orientation: 'portrait',
                    compress: true
                },
                pagebreak: {
                    mode: ['avoid-all', 'css', 'legacy'],
                    before: '.page-break-before',
                    after: '.page-break-after',
                    avoid: ['.avoid-break', '.ingredients-section', '.instructions-section']
                }
            };

            await html2pdf().set(opt as any).from(clone).save();
            return true;
        } catch (error) {
            console.error('Failed to generate PDF:', error);
            throw error;
        }
    };

    const shareViaWhatsApp = (recipe: Recipe) => {
        // Format recipe for WhatsApp
        let message = `🍳 *${recipe.title}*\n\n`;

        if (recipe.description) {
            message += `${recipe.description}\n\n`;
        }

        // Add quick stats
        message += `⏱️ *Prep:* ${recipe.prepTime} | *Cook:* ${recipe.cookTime}\n`;
        message += `👥 *Servings:* ${recipe.servings}`;
        if (recipe.temperature) {
            message += ` | 🌡️ *Temp:* ${recipe.temperature}`;
        }
        message += '\n\n';

        // Add ingredients
        message += `📋 *INGREDIENTS*\n`;
        recipe.ingredients.forEach((ingredient, index) => {
            message += `${index + 1}. ${ingredient}\n`;
        });
        message += '\n';

        // Add instructions
        message += `👨‍🍳 *INSTRUCTIONS*\n`;
        recipe.instructions.forEach((instruction, index) => {
            message += `*Step ${index + 1}:* ${instruction}\n\n`;
        });

        // Add tags if available
        if (recipe.tags && recipe.tags.length > 0) {
            message += `🏷️ ${recipe.tags.join(', ')}\n\n`;
        }

        // Add source/attribution
        message += `_Generated by Liberian Kitchen AI_ 🇱🇷`;

        // Encode message for URL
        const encodedMessage = encodeURIComponent(message);

        // Create WhatsApp URL (works on both mobile and desktop)
        const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
        const whatsappUrl = isMobile
            ? `whatsapp://send?text=${encodedMessage}`
            : `https://web.whatsapp.com/send?text=${encodedMessage}`;

        // Open WhatsApp
        window.open(whatsappUrl, '_blank');

        return true;
    };

    const copyRecipeText = (recipe: Recipe): string => {
        let text = `${recipe.title}\n${'='.repeat(recipe.title.length)}\n\n`;

        if (recipe.description) {
            text += `${recipe.description}\n\n`;
        }

        text += `QUICK INFO\n`;
        text += `Prep Time: ${recipe.prepTime}\n`;
        text += `Cook Time: ${recipe.cookTime}\n`;
        text += `Servings: ${recipe.servings}\n`;
        if (recipe.temperature) {
            text += `Temperature: ${recipe.temperature}\n`;
        }
        text += '\n';

        text += `INGREDIENTS\n`;
        text += `-----------\n`;
        recipe.ingredients.forEach((ingredient, index) => {
            text += `${index + 1}. ${ingredient}\n`;
        });
        text += '\n';

        text += `INSTRUCTIONS\n`;
        text += `------------\n`;
        recipe.instructions.forEach((instruction, index) => {
            text += `Step ${index + 1}: ${instruction}\n\n`;
        });

        if (recipe.tags && recipe.tags.length > 0) {
            text += `Tags: ${recipe.tags.join(', ')}\n`;
        }

        return text;
    };

    const shareRecipe = async (recipe: Recipe) => {
        const text = copyRecipeText(recipe);
        const shareData = {
            title: recipe.title,
            text: text,
            url: window.location.href
        };

        // Use native share API if available
        if (navigator.share) {
            try {
                await navigator.share(shareData);
                return true;
            } catch (error) {
                if ((error as Error).name !== 'AbortError') {
                    console.error('Error sharing:', error);
                }
            }
        }

        // Fallback: copy to clipboard
        try {
            await navigator.clipboard.writeText(text);
            return 'copied';
        } catch (error) {
            console.error('Failed to copy:', error);
            return false;
        }
    };

    return {
        downloadAsPDF,
        shareViaWhatsApp,
        copyRecipeText,
        shareRecipe
    };
};
