import React from 'react';
import { HashRouter as Router, Routes, Route } from 'react-router-dom';
import { Header } from './components/Header';
import { Home } from './pages/Home';
import { RecipeDetails } from './pages/RecipeDetails';
import { SavedRecipes } from './pages/SavedRecipes';
import { Community } from './pages/Community';
import { History } from './pages/History';
import { Profile } from './pages/Profile';
import { AuthProvider } from './contexts/AuthContext';

function App() {
  return (
    <AuthProvider>
      <Router>
        <div className="flex flex-col min-h-screen font-sans text-stone-800">
          <Header />
          <main className="flex-grow">
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/community" element={<Community />} />
              <Route path="/saved" element={<SavedRecipes />} />
              <Route path="/history" element={<History />} />
              <Route path="/profile" element={<Profile />} />
              <Route path="/recipe/:id" element={<RecipeDetails />} />
            </Routes>
          </main>
          <footer className="bg-white border-t border-stone-200 py-8 text-center text-stone-500 text-sm print:hidden">
            <p>© {new Date().getFullYear()} Liberian Kitchen AI. All rights reserved.</p>
            <p className="mt-1">Generated by Google Gemini.</p>
          </footer>
        </div>
      </Router>
    </AuthProvider>
  );
}

export default App;